name: Greeting Workflow

on: [push]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Print Greeting
              run: echo "[+] GitHub action successfuly triggered."
