name: Greeting Workflow

on: [push]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                sparse-checkout: .

            - name: Print Greeting
              run: echo "[+] Action successfuly triggered."
